# Generated by Django 5.2.5 on 2025-10-23 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelTable(
            name='answer',
            table='answers',
        ),
    ]
